# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\"\x1c\n\x0bUserRequest\x12\r\n\x05token\x18\x01 \x01(\t\"}\n\x0cUserResponse\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x11\n\tfirstname\x18\x03 \x01(\t\x12\x0f\n\x07midname\x18\x04 \x01(\t\x12\x10\n\x08lastname\x18\x05 \x01(\t\x12\x14\n\x0cis_superuser\x18\x06 \x01(\x08\"\x1c\n\x0c\x43odeResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x32\x62\n\x04\x41uth\x12+\n\x0c\x61uthenticate\x12\x0c.UserRequest\x1a\r.UserResponse\x12-\n\x0e\x64\x65\x61uthenticate\x12\x0c.UserRequest\x1a\r.CodeResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _USERREQUEST._serialized_start=14
  _USERREQUEST._serialized_end=42
  _USERRESPONSE._serialized_start=44
  _USERRESPONSE._serialized_end=169
  _CODERESPONSE._serialized_start=171
  _CODERESPONSE._serialized_end=199
  _AUTH._serialized_start=201
  _AUTH._serialized_end=299
# @@protoc_insertion_point(module_scope)
